iws.version=2.0
ws.iws.gen.authenticationmethod=*NONE
ws.iws.gen.autostartup=true
ws.iws.gen.defaultschema=CLAIMS
ws.iws.gen.messagelogging=false
ws.iws.gen.methodlist=GETALL,GETBYID
ws.iws.gen.securetransportrequired=false
ws.iws.gen.servicedescription=policy web service
ws.iws.gen.servicename=policy
ws.iws.gen.servicetype=*REST
ws.iws.gen.serviceuserid=*SERVER
ws.iws.gen.uripathtemplate=/
ws.iws.gen.useparamnameaselementname=false
ws.iws.gen.usepgmlanguageidentifiers=true
ws.iws.jdbc.access=all
ws.iws.jdbc.auto\ commit=true
ws.iws.jdbc.autocommit\ exception=false
ws.iws.jdbc.bidi\ implicit\ reordering=true
ws.iws.jdbc.bidi\ numeric\ ordering=false
ws.iws.jdbc.bidi\ string\ type=5
ws.iws.jdbc.big\ decimal=true
ws.iws.jdbc.block\ criteria=2
ws.iws.jdbc.block\ size=32
ws.iws.jdbc.character\ truncation=true
ws.iws.jdbc.concurrent\ access\ resolution=2
ws.iws.jdbc.cursor\ hold=true
ws.iws.jdbc.cursor\ sensitivity=asensitive
ws.iws.jdbc.data\ compression=true
ws.iws.jdbc.data\ truncation=true
ws.iws.jdbc.date\ format=iso
ws.iws.jdbc.decfloat\ rounding\ mode=half even
ws.iws.jdbc.decimal\ separator=
ws.iws.jdbc.driver=toolbox
ws.iws.jdbc.errors=basic
ws.iws.jdbc.extended\ dynamic=false
ws.iws.jdbc.extended\ metadata=false
ws.iws.jdbc.full\ open=false
ws.iws.jdbc.hold\ input\ locators=true
ws.iws.jdbc.hold\ statements=false
ws.iws.jdbc.ignore\ warnings=01003,0100C,01567
ws.iws.jdbc.lazy\ close=false
ws.iws.jdbc.libraries=*LIBL
ws.iws.jdbc.lob\ threshold=32768
ws.iws.jdbc.maximum\ blocked\ input\ rows=32000
ws.iws.jdbc.maximum\ precision=31
ws.iws.jdbc.maximum\ scale=31
ws.iws.jdbc.metadata\ source=1
ws.iws.jdbc.minimum\ divide\ scale=0
ws.iws.jdbc.naming=sql
ws.iws.jdbc.numeric\ range\ error=true
ws.iws.jdbc.package=
ws.iws.jdbc.package\ add=true
ws.iws.jdbc.package\ cache=false
ws.iws.jdbc.package\ ccsid=13488
ws.iws.jdbc.package\ criteria=default
ws.iws.jdbc.package\ error=warning
ws.iws.jdbc.package\ library=QGPL
ws.iws.jdbc.portNumber=0
ws.iws.jdbc.prefetch=true
ws.iws.jdbc.proxy\ server=
ws.iws.jdbc.qaqqinilib=
ws.iws.jdbc.query\ optimize\ goal=0
ws.iws.jdbc.query\ replace\ truncated\ parameter=
ws.iws.jdbc.query\ storage\ limit=-1
ws.iws.jdbc.query\ timeout\ mechanism=qqrytimlmt
ws.iws.jdbc.remarks=system
ws.iws.jdbc.secondary\ URL=
ws.iws.jdbc.server\ trace=0
ws.iws.jdbc.sort=hex
ws.iws.jdbc.sort\ language=
ws.iws.jdbc.sort\ table=
ws.iws.jdbc.sort\ weight=shared
ws.iws.jdbc.time\ format=iso
ws.iws.jdbc.trace=false
ws.iws.jdbc.transaction\ isolation=read uncommitted
ws.iws.jdbc.translate\ binary=false
ws.iws.jdbc.translate\ boolean=true
ws.iws.jdbc.translate\ hex=character
ws.iws.jdbc.true\ autocommit=false
ws.iws.jdbc.use\ block\ update=false
ws.iws.jdbc.variable\ field\ compression=all
ws.iws.jdbc.XA\ loosely\ coupled\ support=0
ws.iws.pool.ccsid=*USERID
ws.iws.pool.cleanupinterval=300
ws.iws.pool.fillcount=1
ws.iws.pool.hostserver=localhost
ws.iws.pool.maxconnections=*NOMAX
ws.iws.pool.maxinactivity=3600
ws.iws.pool.maxlifetime=86400
ws.iws.pool.maxusecount=*NOMAX
ws.iws.pool.maxusetime=*NOMAX
ws.iws.pool.usessl=false
ws.iws.pool.usethreads=true
ws.method.GETALL.gen.consumes=*/*
ws.method.GETALL.gen.errormessage=
ws.method.GETALL.gen.errorparam=
ws.method.GETALL.gen.httpfailurecode=500
ws.method.GETALL.gen.httpheaders=*NONE
ws.method.GETALL.gen.httprequestmethod=GET
ws.method.GETALL.gen.httpsuccesscode=200
ws.method.GETALL.gen.inputwrapperidentifier=GETALLInput
ws.method.GETALL.gen.outputwrapperidentifier=GETALLResult
ws.method.GETALL.gen.produces=application/json
ws.method.GETALL.gen.querytype=multi-row
ws.method.GETALL.gen.returnsqlstate=*ERRORS
ws.method.GETALL.gen.treatwarningaserror=true
ws.method.GETALL.gen.trimmode=*TRAILING
ws.method.GETALL.gen.uripathtemplate=
ws.method.GETALL.gen.wrapinparams=false
ws.method.GETALL.gen.wrapoutparam=true
ws.method.GETBYID.gen.consumes=*/*
ws.method.GETBYID.gen.errormessage=
ws.method.GETBYID.gen.errorparam=
ws.method.GETBYID.gen.httpfailurecode=500
ws.method.GETBYID.gen.httpheaders=*NONE
ws.method.GETBYID.gen.httprequestmethod=GET
ws.method.GETBYID.gen.httpsuccesscode=200
ws.method.GETBYID.gen.inputwrapperidentifier=GETBYIDInput
ws.method.GETBYID.gen.outputwrapperidentifier=GETBYIDResult
ws.method.GETBYID.gen.produces=application/json
ws.method.GETBYID.gen.querytype=single-row
ws.method.GETBYID.gen.returnsqlstate=*ERRORS
ws.method.GETBYID.gen.treatwarningaserror=true
ws.method.GETBYID.gen.trimmode=*TRAILING
ws.method.GETBYID.gen.uripathtemplate={id}
ws.method.GETBYID.gen.wrapinparams=false
ws.method.GETBYID.gen.wrapoutparam=true
ws.method.GETBYID.param.policyID.pathparam=id
ws.method.GETBYID.param.policyID.usage=input
